#!/bin/bash
. $(dirname $(readlink -f "${BASH_SOURCE[0]}"))/logger

performTests() {
  local task_dir=$2
  local tests_dir=$1
  cd $task_dir
  if [ -x $tests_dir/setup ] ; then $tests_dir/setup ; fi
  for t in $tests_dir/test*; do 
    export TESTNAME=$(basename $t)
    if [ -x $t ] ; then
      if $t ; then
        logOk "$TESTNAME passed"
      else
        logWarn "Failed"
      fi
    else
      logWarn "$TESTNAME skipped"
    fi
  done
}

forTask() {
  local task_src_dir="$1"
  export TASKNAME=$(basename $task_src_dir)
  local tests="$TESTS_ROOT_DIR"/"$TASKNAME"
  if ! [ -d $tests ] ; then
    logError "Incorrect task directory name"
  else
    performTests "$tests" "$task_src_dir"
  fi
}

forAllTasks() {
  # cd "$1" && pwd
  for t in $(allDirsIn "$1") ; do 
    forTask "$t"
  done 
}

isUserDir() {
  [ -d "$1" ]
}

forUser() {
  local u="$1"
  export USERNAME=$(basename $u)
  if isUserDir "$u" ; then  forAllTasks "$u" ; fi
}

forAllUsers() {
  local IFS=$'\n'
  for u in $(allDirsIn "$1");    do  forUser "$u" ; done
}

setStatus() {
  local errorsCnt=$1
  ((errorsCnt > 1)) && echo 123 || echo 0
}

