#!/bin/bash
. $(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../logger
#echo "Running $TESTNAME for task $TASKNAME of user $USERNAME in $PWD with $# parameters: $*"
listAllFiles(){
  env LC_ALL=C find . -mindepth 1 -maxdepth 1 -type f | sort -u
}
checkMandatoryFiles() {
  [ -n "$1" ]
  local files=$(listAllFiles)
  for x in $* ; do
   if [[ "$files" == *$x* ]] ; then true ; else logError "Missing mandatory file $x" ; fi
  done
}
checkMandatoryFiles $MANDATORY_SOURCES
