#!/bin/bash
. $(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../logger

checkProhibitedFiles() {
  local ifs=$IFS
  IFS=$(echo -en "\n\b")
  local files=$(env LC_ALL=C find . -type f )
  for x in $files ; do
    local type="$(file -b --mime-type $x)"
      [[ "$x" =~ ^[!-z]*$ ]] &&\
      case "$type" in
        image/*) (( $(wc -c < "$x") < 200000 )) ;;
        text/x-*) (( $(wc -l < "$x") < 300 )) ;;
        text/plain) (( $(wc -l < "$x") < 200 )) && (( $(wc -c < "$x") < 20000 )) ;;

        *) false;;
      esac \
    || logWarn "Strange file \"$x\""
  done
  IFS=$ifs
  unset ifs
}

checkProhibitedFiles
