#!/bin/bash
. $(dirname $(readlink -f "${BASH_SOURCE[0]}"))/../logger

checkTabsAndSpaces() {
	local err=0
	local res=""
	res=$(gawk -F '[^[:space:]]+' -e '/^[[:space:]]+/{ tabs+=gsub(/\t/,1,$1); spcs+=gsub(/ /,2,$1) ;} END{res=((spcs < tabs)? (spcs " spaces but uses tabs"): (tabs " tabs but uses spaces")); print(FILENAME ":", res); exit(tabs*spcs?1:0);}' "$1") || err=$?
	if (( $err )) ; then
		logError "Ugly mixture of tabs and spaces found in $res"
	fi
	unset err
	unset res
}

checkTabsAndSpacesForAllSources() {
	local srcs=$(env LC_ALL=C\
		find . -mindepth 1 -maxdepth 1 -type f -name '*.c' -o -name '*.h'\
		| sort -u)
	for s in "$srcs" ; do
		checkTabsAndSpaces $s
	done
}

checkTabsAndSpacesForAllSources
